/**
 * Token re-exports — provides typed access to all generated Morpheus tokens.
 * Source of truth: /tokens/*.json → Style Dictionary → /build/morph-tokens.ts
 */
export {
  // Neutral palette
  ColorNeutral0,
  ColorNeutral50,
  ColorNeutral100,
  ColorNeutral150,
  ColorNeutral200,
  ColorNeutral300,
  ColorNeutral400,
  ColorNeutral500,
  ColorNeutral600,
  ColorNeutral700,
  ColorNeutral800,
  ColorNeutral850,
  ColorNeutral900,
  ColorNeutral950,
  ColorNeutral1000,
  // Accent palette
  ColorAccent100,
  ColorAccent200,
  ColorAccent300,
  ColorAccent400,
  ColorAccent500,
  ColorAccent600,
  ColorAccent700,
  ColorAccent800,
  ColorAccent900,
  // Status
  ColorStatusDanger,
  ColorStatusDangerOnDark,
  ColorStatusWarning,
  ColorStatusWarningOnDark,
  ColorStatusSuccess,
  ColorStatusSuccessOnDark,
  ColorStatusInfo,
  ColorStatusInfoOnDark,
  // Space
  MorphSpace0,
  MorphSpace1,
  MorphSpace2,
  MorphSpace3,
  MorphSpace4,
  MorphSpace5,
  MorphSpace6,
  MorphSpace7,
  MorphSpace8,
  MorphSpace9,
  MorphSpace10,
  // Radius
  MorphRadius0,
  MorphRadius1,
  MorphRadius2,
  MorphRadius3,
  MorphRadius4,
  MorphRadiusFull,
  // Motion
  MorphMotionDurationT1,
  MorphMotionDurationT2,
  MorphMotionDurationT3,
  MorphMotionDurationT4,
  MorphMotionDurationT5,
  MorphMotionEasingStandard,
  MorphMotionEasingEntrance,
  MorphMotionEasingExit,
  MorphMotionSpringDefault,
  MorphMotionSpringPress,
  // Typography
  MorphTypeFamilyUi,
  MorphTypeFamilyDisplay,
  MorphTypeFamilyMono,
  // Breakpoints
  MorphBreakpointXs,
  MorphBreakpointSm,
  MorphBreakpointMd,
  MorphBreakpointLg,
  MorphBreakpointXl,
  MorphBreakpoint2xl,
  // Alias (dark default)
  MorphColorGround,
  MorphColorSurface,
  MorphColorSurfaceRaised,
  MorphColorSurfaceOverlay,
  MorphColorOnSurface,
  MorphColorOnSurfaceMuted,
  MorphColorBorderSubtle,
  MorphColorAccent,
  MorphColorAccentText,
  MorphColorOnAccent,
  MorphColorFocus,
} from "../../build/morph-tokens";
